services:
  - type: web
    name: aptbarber
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    repo: https://github.com/oswydevops/aptbarber.git
    branch: master
    autoDeploy: true